# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoramas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoramastore',
            name='zip_file',
        ),
    ]
