# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-03 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panoramas', '0002_remove_panoramastore_zip_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panoramastore',
            name='description',
        ),
        migrations.RemoveField(
            model_name='panoramastore',
            name='store_path',
        ),
    ]
