# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160417_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(help_text='Для главной страницы и SEO', verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name_plural': 'услуги',
                'verbose_name': 'услуга',
            },
        ),
    ]
