# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_services_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(help_text='Для главной страницы и SEO', verbose_name='Краткое описание')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/%d', verbose_name='Превью')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='URL')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
                ('on_main', models.BooleanField(default=False, verbose_name='На главной')),
                ('panorama_url', models.URLField(blank=True, null=True, verbose_name='URL на панораму')),
            ],
            options={
                'verbose_name': 'портфолио',
                'verbose_name_plural': 'портфолио',
            },
        ),
    ]
