# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panoramas', '0002_remove_panoramastore_zip_file'),
        ('main', '0007_auto_20160712_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='panorama_url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panoramas.PanoramaStore', verbose_name='Панорама'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='services',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
    ]
