# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='URL')),
                ('store_path', models.CharField(editable=False, max_length=200, unique=True, verbose_name='Относительный путь к хранилищу')),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Архив для обработки')),
            ],
            options={
                'verbose_name': 'панорама',
                'verbose_name_plural': 'панорамы',
            },
        ),
    ]
