# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Контакнтый номер')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Services', verbose_name='Интересующая услуга')),
            ],
            options={
                'verbose_name': 'обратная связь',
                'verbose_name_plural': 'обратная связь',
            },
        ),
    ]
