# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.Services._get_path_and_rename_file, verbose_name='Изображение'),
        ),
    ]
